# File:    ms-build-config.ps1
# Author:  Garrett Carter
# Purpose: Build a config (passed in param) in Microchip Studio using bundled command-line tools
param (
    # Makefile generated by Atmel Studio is located in the config_folder
    [Parameter(Mandatory)]
    [string]
    $config_folder,
    # The executable name within the config_folder, without an extension. Ex. neo_driver_app
    [Parameter(Mandatory)]
    [string]
    $exec_name,
    [Parameter(Mandatory=$false)]
    [ValidateSet("true", "false")]
    [string]
    $clean_build = "false"
)

$ErrorActionPreference = 'Stop'
if (-Not (Get-Command atprogram.exe -ErrorAction SilentlyContinue)) {
    Write-Host "Adding Atmel Studio dirs to process PATH variable..."
    $Env:PATH = "C:\Program Files (x86)\Atmel\Studio\7.0\;C:\Program Files (x86)\Atmel\Studio\7.0\shellutils\;C:\Program Files (x86)\Atmel\Studio\7.0\atbackend\;C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\;$Env:PATH"
}
$config_folder = [System.IO.Path]::GetFullPath($config_folder)

# Use verbose flag for atprogram commands? 1 for yes, 0 for no
$atprog_use_verbose = 0

if ($atprog_use_verbose -eq 1){
    $atprog_verbose = "-v"
} else {
    $atprog_verbose = $null
}

# Must be in folder with Makefile
Set-Location $config_folder

# Do a clean first, if required
if ($clean_build -eq "true") {
    make.exe clean
    if ($LASTEXITCODE -ne 0) {
        Exit $LASTEXITCODE
    }    
}

make.exe all --jobs 8 --output-sync
if ($LASTEXITCODE -ne 0) {
    Exit $LASTEXITCODE
}

& $PSScriptRoot\ms-get-size-info.ps1 -elf_to_parse "${config_folder}\${exec_name}.elf" -output_text_file "${config_folder}\${exec_name}_syms.txt"
if ($LASTEXITCODE -ne 0) {
    Exit $LASTEXITCODE
}

Exit 0